AWSTemplateFormatVersion: '2010-09-09'
Description: Resources needed to deploy scheduled lambda function.
Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: "test-repository"
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          -
            Sid: AllowPushPull
            Effect: Allow
            Principal:
              AWS:
                - "arn:aws:iam::257492816994:user/aws-lambda-demo-user"
            Action:
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:PutImage"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"
  LambdaFunction:
    Type: AWS::Lambda::Function
    DependsOn: ECRRepository
    Properties:
      FunctionName: my-func-name-lambda-func  # optional
      Description: A starter AWS Lambda function.
      Role: arn:aws:iam::257492816994:role/aws-lambda-role
      PackageType: Image
      Code:
        ImageUri: 257492816994.dkr.ecr.us-east-1.amazonaws.com/test:latest
      Timeout: 30
      MemorySize: 128
      TracingConfig:
        Mode: Active
      # VpcConfig:
      #   SecurityGroupIds:
      #     - sg-0d1d60471d00b3c5e
      #   SubnetIds:
      #     - subnet-04564f21a448f7a97
      #     - subnet-00553e385bc6a7f1c
  ScheduledRule:
    Type: AWS::Events::Rule
    DependsOn: LambdaFunction
    Properties:
      Name: my-func-name-cloudwatch # optional
      Description: "ScheduledRule"
      ScheduleExpression: "cron(00 12 ? * MON-FRI *)"
      State: "ENABLED"
      Targets:
        -
          Arn:
            Fn::GetAtt:
              - "LambdaFunction"
              - "Arn"
          Id: "TargetFunctionV1"
  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    DependsOn: LambdaFunction
    Properties:
      FunctionName: !Ref "LambdaFunction"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn:
        Fn::GetAtt:
          - "ScheduledRule"
          - "Arn"
